# -*- coding: utf-8 -*-
"""listy jednokierunkowe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_KtaqTcAhlZs4866VJ4HP0bg0yibaTD
"""

class elem:
  def __init__(self):
    self.wartosc = None
    self.nastepny = None
class lista:
  def __init__(self):
    self.poczatek = None
  def dodaj(self, wartosc):
    iter = self.poczatek
    if iter is None:
        nowy = elem()
        nowy.wartosc = wartosc
        self.poczatek = nowy
        return
    if iter.wartosc > wartosc:
        nowy = elem()
        nowy.wartosc = wartosc
        nowy.nastepny = iter
        self.poczatek = nowy
        return
    while iter.nastepny is not None:
        if iter.nastepny.wartosc > wartosc:
            break
        iter = iter.nastepny
    nowy = elem()
    nowy.wartosc = wartosc
    nowy.nastepny = iter.nastepny
    iter.nastepny = nowy

    return
  
  
  def usun(self, wartosc):
    iter = self.poczatek
    if iter.wartosc == wartosc:
      self.poczatek = iter.nastepny
      return
    while iter is not None:
      if iter.wartosc == wartosc:
        break
      poprzedni = iter
      iter = iter.nastepny
    poprzedni.nastepny = iter.nastepny    
    
    
    
  def poka(self):
    iter = self.poczatek
    while iter is not None:
      if iter.nastepny is None:
        print(iter.wartosc)
      else: print(iter.wartosc, end = ',')
      iter = iter.nastepny
    return
l = lista()     
l.dodaj(5)
l.dodaj(6)
l.dodaj(3)
l.poka()
l.usun(3)
l.poka()
l.usun(5)
l.poka()